export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type PromoCampaignStatus = "draft" | "live" | "paused" | "closed" | "locked" | "drawn" | "archived";
export type CommerceOfferStatus = "draft" | "active" | "paused" | "archived";
export type OrderStatus = "pending" | "paid" | "fulfilled" | "payment_failed" | "cancelled" | "refunded";
export type AccessGrantStatus = "pending_activation" | "active" | "expired" | "revoked";
export type AccessGrantType = "daypass" | "ultra" | "admin_comp" | "manual_comp";
export type DaypassCodeStatus = "available" | "redeemed" | "expired" | "revoked";
export type PromoEntryStatus = "active" | "cancelled" | "refunded" | "void" | "winner" | "disqualified";
export type ListingStatus = "draft" | "live" | "paused" | "archived";
export type OutboundEmailStatus = "queued" | "sent" | "failed" | "skipped";
export type StripeWebhookProcessingStatus = "received" | "processing" | "processed" | "ignored" | "failed";

export type Database = {
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          id: string;
          email: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      landing_page_tests: {
        Row: {
          id: string;
          slug: string;
          status: string;
          internal_name: string;
          headline: string;
          subheadline: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string;
          price_display: string | null;
          category_focus: string | null;
          cta_primary: string | null;
          cta_secondary: string | null;
          modal_headline: string | null;
          modal_body: string | null;
          waitlist_cta: string | null;
          hero_image_url: string | null;
          config_json: Json;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          status?: string;
          internal_name: string;
          headline: string;
          subheadline?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          price_display?: string | null;
          category_focus?: string | null;
          cta_primary?: string | null;
          cta_secondary?: string | null;
          modal_headline?: string | null;
          modal_body?: string | null;
          waitlist_cta?: string | null;
          hero_image_url?: string | null;
          config_json?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          status?: string;
          internal_name?: string;
          headline?: string;
          subheadline?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          price_display?: string | null;
          category_focus?: string | null;
          cta_primary?: string | null;
          cta_secondary?: string | null;
          modal_headline?: string | null;
          modal_body?: string | null;
          waitlist_cta?: string | null;
          hero_image_url?: string | null;
          config_json?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      waitlist_leads: {
        Row: {
          id: string;
          email: string;
          email_normalized: string;
          first_name: string | null;
          source_landing_page_id: string | null;
          source_slug: string | null;
          anonymous_id: string | null;
          session_id: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          meta_campaign_id: string | null;
          meta_adset_id: string | null;
          meta_ad_id: string | null;
          offer_id: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string;
          fbclid: string | null;
          path: string | null;
          referrer: string | null;
          device_type: string | null;
          budget_range: string | null;
          buyer_seller_intent: string | null;
          likelihood_to_buy: string | null;
          consent_marketing: boolean;
          consent_marketing_at: string | null;
          privacy_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          email_normalized: string;
          first_name?: string | null;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          fbclid?: string | null;
          path?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          budget_range?: string | null;
          buyer_seller_intent?: string | null;
          likelihood_to_buy?: string | null;
          consent_marketing?: boolean;
          consent_marketing_at?: string | null;
          privacy_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          email_normalized?: string;
          first_name?: string | null;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          fbclid?: string | null;
          path?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          budget_range?: string | null;
          buyer_seller_intent?: string | null;
          likelihood_to_buy?: string | null;
          consent_marketing?: boolean;
          consent_marketing_at?: string | null;
          privacy_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_preferences: {
        Row: {
          id: string;
          lead_id: string | null;
          preference_type: string;
          preference_value: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id?: string | null;
          preference_type: string;
          preference_value: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string | null;
          preference_type?: string;
          preference_value?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      event_logs: {
        Row: {
          id: string;
          event_name: string;
          anonymous_id: string | null;
          session_id: string | null;
          lead_id: string | null;
          landing_page_id: string | null;
          landing_slug: string | null;
          offer_id: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string | null;
          path: string | null;
          url: string | null;
          referrer: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          fbclid: string | null;
          meta_campaign_id: string | null;
          meta_adset_id: string | null;
          meta_ad_id: string | null;
          device_type: string | null;
          properties: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_name: string;
          anonymous_id?: string | null;
          session_id?: string | null;
          lead_id?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string | null;
          path?: string | null;
          url?: string | null;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          device_type?: string | null;
          properties?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_name?: string;
          anonymous_id?: string | null;
          session_id?: string | null;
          lead_id?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string | null;
          path?: string | null;
          url?: string | null;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          device_type?: string | null;
          properties?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      visitor_sessions: {
        Row: {
          id: string;
          session_id: string;
          anonymous_id: string;
          first_seen_at: string;
          last_seen_at: string;
          entry_path: string | null;
          landing_page_id: string | null;
          landing_slug: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          device_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          anonymous_id: string;
          first_seen_at?: string;
          last_seen_at?: string;
          entry_path?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          anonymous_id?: string;
          first_seen_at?: string;
          last_seen_at?: string;
          entry_path?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      export_logs: {
        Row: {
          id: string;
          admin_user_id: string | null;
          export_type: string;
          filters_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_user_id?: string | null;
          export_type: string;
          filters_json?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          admin_user_id?: string | null;
          export_type?: string;
          filters_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      member_profiles: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          email_normalized: string;
          display_name: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email: string;
          email_normalized: string;
          display_name?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string;
          email_normalized?: string;
          display_name?: string | null;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      promo_campaigns: {
        Row: {
          id: string;
          slug: string;
          status: PromoCampaignStatus;
          name: string;
          short_name: string | null;
          prize_title: string;
          prize_description: string | null;
          prize_value_cents: number | null;
          currency: string;
          entry_limit: number | null;
          starts_at: string | null;
          closes_at: string | null;
          entries_close_at: string | null;
          draw_lock_at: string | null;
          draw_at: string | null;
          rules_url: string | null;
          terms_version: string | null;
          config_json: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          status?: PromoCampaignStatus;
          name: string;
          short_name?: string | null;
          prize_title: string;
          prize_description?: string | null;
          prize_value_cents?: number | null;
          currency?: string;
          entry_limit?: number | null;
          starts_at?: string | null;
          closes_at?: string | null;
          entries_close_at?: string | null;
          draw_lock_at?: string | null;
          draw_at?: string | null;
          rules_url?: string | null;
          terms_version?: string | null;
          config_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          status?: PromoCampaignStatus;
          name?: string;
          short_name?: string | null;
          prize_title?: string;
          prize_description?: string | null;
          prize_value_cents?: number | null;
          currency?: string;
          entry_limit?: number | null;
          starts_at?: string | null;
          closes_at?: string | null;
          entries_close_at?: string | null;
          draw_lock_at?: string | null;
          draw_at?: string | null;
          rules_url?: string | null;
          terms_version?: string | null;
          config_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      commerce_offers: {
        Row: {
          id: string;
          code: string;
          status: CommerceOfferStatus;
          name: string;
          offer_type: string;
          stripe_price_id: string | null;
          unit_price_cents: number;
          currency: string;
          access_duration_hours: number | null;
          config_json: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          status?: CommerceOfferStatus;
          name: string;
          offer_type: string;
          stripe_price_id?: string | null;
          unit_price_cents: number;
          currency?: string;
          access_duration_hours?: number | null;
          config_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          status?: CommerceOfferStatus;
          name?: string;
          offer_type?: string;
          stripe_price_id?: string | null;
          unit_price_cents?: number;
          currency?: string;
          access_duration_hours?: number | null;
          config_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          member_profile_id: string | null;
          purchaser_email: string | null;
          purchaser_email_normalized: string | null;
          stripe_customer_id: string | null;
          stripe_checkout_session_id: string | null;
          stripe_payment_intent_id: string | null;
          status: OrderStatus;
          subtotal_cents: number;
          total_cents: number;
          currency: string;
          source_landing_page_id: string | null;
          source_slug: string | null;
          anonymous_id: string | null;
          session_id: string | null;
          attribution_json: Json;
          created_at: string;
          updated_at: string;
          fulfilled_at: string | null;
        };
        Insert: {
          id?: string;
          member_profile_id?: string | null;
          purchaser_email?: string | null;
          purchaser_email_normalized?: string | null;
          stripe_customer_id?: string | null;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          status?: OrderStatus;
          subtotal_cents?: number;
          total_cents?: number;
          currency?: string;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          attribution_json?: Json;
          created_at?: string;
          updated_at?: string;
          fulfilled_at?: string | null;
        };
        Update: {
          id?: string;
          member_profile_id?: string | null;
          purchaser_email?: string | null;
          purchaser_email_normalized?: string | null;
          stripe_customer_id?: string | null;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          status?: OrderStatus;
          subtotal_cents?: number;
          total_cents?: number;
          currency?: string;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          attribution_json?: Json;
          created_at?: string;
          updated_at?: string;
          fulfilled_at?: string | null;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          offer_id: string | null;
          campaign_id: string | null;
          item_type: string;
          quantity: number;
          unit_price_cents: number;
          total_price_cents: number;
          currency: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          offer_id?: string | null;
          campaign_id?: string | null;
          item_type: string;
          quantity: number;
          unit_price_cents: number;
          total_price_cents: number;
          currency?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          offer_id?: string | null;
          campaign_id?: string | null;
          item_type?: string;
          quantity?: number;
          unit_price_cents?: number;
          total_price_cents?: number;
          currency?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      access_grants: {
        Row: {
          id: string;
          member_profile_id: string | null;
          order_id: string | null;
          order_item_id: string | null;
          daypass_code_id: string | null;
          access_type: AccessGrantType;
          status: AccessGrantStatus;
          starts_at: string | null;
          expires_at: string | null;
          created_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          member_profile_id?: string | null;
          order_id?: string | null;
          order_item_id?: string | null;
          daypass_code_id?: string | null;
          access_type: AccessGrantType;
          status?: AccessGrantStatus;
          starts_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          member_profile_id?: string | null;
          order_id?: string | null;
          order_item_id?: string | null;
          daypass_code_id?: string | null;
          access_type?: AccessGrantType;
          status?: AccessGrantStatus;
          starts_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [];
      };
      daypass_codes: {
        Row: {
          id: string;
          purchaser_member_profile_id: string | null;
          purchaser_email_normalized: string;
          order_id: string | null;
          order_item_id: string | null;
          campaign_id: string | null;
          code_hash: string;
          code_last4: string;
          encrypted_code: string | null;
          encryption_key_version: string | null;
          status: DaypassCodeStatus;
          redeemed_by_member_profile_id: string | null;
          redeemed_at: string | null;
          access_grant_id: string | null;
          created_at: string;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          purchaser_member_profile_id?: string | null;
          purchaser_email_normalized: string;
          order_id?: string | null;
          order_item_id?: string | null;
          campaign_id?: string | null;
          code_hash: string;
          code_last4: string;
          encrypted_code?: string | null;
          encryption_key_version?: string | null;
          status?: DaypassCodeStatus;
          redeemed_by_member_profile_id?: string | null;
          redeemed_at?: string | null;
          access_grant_id?: string | null;
          created_at?: string;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          purchaser_member_profile_id?: string | null;
          purchaser_email_normalized?: string;
          order_id?: string | null;
          order_item_id?: string | null;
          campaign_id?: string | null;
          code_hash?: string;
          code_last4?: string;
          encrypted_code?: string | null;
          encryption_key_version?: string | null;
          status?: DaypassCodeStatus;
          redeemed_by_member_profile_id?: string | null;
          redeemed_at?: string | null;
          access_grant_id?: string | null;
          created_at?: string;
          expires_at?: string | null;
        };
        Relationships: [];
      };
      promo_entries: {
        Row: {
          id: string;
          campaign_id: string;
          order_id: string | null;
          order_item_id: string | null;
          daypass_code_id: string | null;
          entry_number: number;
          owner_member_profile_id: string | null;
          owner_email_normalized: string;
          current_holder_member_profile_id: string | null;
          referrer_member_profile_id: string | null;
          display_alias: string;
          status: PromoEntryStatus;
          locked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          order_id?: string | null;
          order_item_id?: string | null;
          daypass_code_id?: string | null;
          entry_number: number;
          owner_member_profile_id?: string | null;
          owner_email_normalized: string;
          current_holder_member_profile_id?: string | null;
          referrer_member_profile_id?: string | null;
          display_alias: string;
          status?: PromoEntryStatus;
          locked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          order_id?: string | null;
          order_item_id?: string | null;
          daypass_code_id?: string | null;
          entry_number?: number;
          owner_member_profile_id?: string | null;
          owner_email_normalized?: string;
          current_holder_member_profile_id?: string | null;
          referrer_member_profile_id?: string | null;
          display_alias?: string;
          status?: PromoEntryStatus;
          locked_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          id: string;
          slug: string;
          status: ListingStatus;
          title: string;
          brand: string | null;
          deck_year: number | null;
          era: string | null;
          condition_label: string | null;
          price_cents: number | null;
          currency: string;
          location_region: string | null;
          is_featured: boolean;
          is_member_only: boolean;
          primary_image_url: string | null;
          facts_json: Json;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          status?: ListingStatus;
          title: string;
          brand?: string | null;
          deck_year?: number | null;
          era?: string | null;
          condition_label?: string | null;
          price_cents?: number | null;
          currency?: string;
          location_region?: string | null;
          is_featured?: boolean;
          is_member_only?: boolean;
          primary_image_url?: string | null;
          facts_json?: Json;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          status?: ListingStatus;
          title?: string;
          brand?: string | null;
          deck_year?: number | null;
          era?: string | null;
          condition_label?: string | null;
          price_cents?: number | null;
          currency?: string;
          location_region?: string | null;
          is_featured?: boolean;
          is_member_only?: boolean;
          primary_image_url?: string | null;
          facts_json?: Json;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      draw_snapshots: {
        Row: {
          id: string;
          campaign_id: string;
          entry_count: number;
          csv_sha256: string;
          created_by: string | null;
          created_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          entry_count: number;
          csv_sha256: string;
          created_by?: string | null;
          created_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          entry_count?: number;
          csv_sha256?: string;
          created_by?: string | null;
          created_at?: string;
          notes?: string | null;
        };
        Relationships: [];
      };
      draw_results: {
        Row: {
          id: string;
          campaign_id: string;
          draw_snapshot_id: string | null;
          winning_entry_id: string | null;
          winning_entry_number: number;
          draw_method: string;
          public_notes: string | null;
          internal_notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          draw_snapshot_id?: string | null;
          winning_entry_id?: string | null;
          winning_entry_number: number;
          draw_method: string;
          public_notes?: string | null;
          internal_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          draw_snapshot_id?: string | null;
          winning_entry_id?: string | null;
          winning_entry_number?: number;
          draw_method?: string;
          public_notes?: string | null;
          internal_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      outbound_emails: {
        Row: {
          id: string;
          provider: string;
          provider_message_id: string | null;
          recipient_email: string;
          template_key: string;
          idempotency_key: string;
          related_order_id: string | null;
          related_campaign_id: string | null;
          status: OutboundEmailStatus;
          error_message: string | null;
          created_at: string;
          sent_at: string | null;
        };
        Insert: {
          id?: string;
          provider: string;
          provider_message_id?: string | null;
          recipient_email: string;
          template_key: string;
          idempotency_key: string;
          related_order_id?: string | null;
          related_campaign_id?: string | null;
          status?: OutboundEmailStatus;
          error_message?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Update: {
          id?: string;
          provider?: string;
          provider_message_id?: string | null;
          recipient_email?: string;
          template_key?: string;
          idempotency_key?: string;
          related_order_id?: string | null;
          related_campaign_id?: string | null;
          status?: OutboundEmailStatus;
          error_message?: string | null;
          created_at?: string;
          sent_at?: string | null;
        };
        Relationships: [];
      };
      stripe_webhook_events: {
        Row: {
          id: string;
          stripe_event_id: string;
          event_type: string;
          stripe_checkout_session_id: string | null;
          processing_status: StripeWebhookProcessingStatus;
          related_order_id: string | null;
          payload_json: Json | null;
          error_message: string | null;
          received_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          stripe_event_id: string;
          event_type: string;
          stripe_checkout_session_id?: string | null;
          processing_status?: StripeWebhookProcessingStatus;
          related_order_id?: string | null;
          payload_json?: Json | null;
          error_message?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          stripe_event_id?: string;
          event_type?: string;
          stripe_checkout_session_id?: string | null;
          processing_status?: StripeWebhookProcessingStatus;
          related_order_id?: string | null;
          payload_json?: Json | null;
          error_message?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      promo_campaign_entry_counters: {
        Row: {
          campaign_id: string;
          last_entry_number: number;
          updated_at: string;
        };
        Insert: {
          campaign_id: string;
          last_entry_number?: number;
          updated_at?: string;
        };
        Update: {
          campaign_id?: string;
          last_entry_number?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      fulfill_daypass_order: {
        Args: {
          p_stripe_event_id: string;
          p_order_id: string;
          p_stripe_checkout_session_id: string;
          p_stripe_customer_id: string | null;
          p_stripe_payment_intent_id: string | null;
          p_purchaser_email: string;
          p_purchaser_email_normalized: string;
          p_campaign_id: string;
          p_offer_id: string;
          p_quantity: number;
          p_friend_codes: Json;
          p_webhook_payload?: Json;
        };
        Returns: Json;
      };
      redeem_daypass_code: {
        Args: {
          p_code_hash: string;
          p_redeemer_member_profile_id: string;
          p_now?: string;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type AdminProfile = Database["public"]["Tables"]["admin_profiles"]["Row"];
export type LandingPageTest = Database["public"]["Tables"]["landing_page_tests"]["Row"];
export type WaitlistLead = Database["public"]["Tables"]["waitlist_leads"]["Row"];
export type LeadPreference = Database["public"]["Tables"]["lead_preferences"]["Row"];
export type EventLog = Database["public"]["Tables"]["event_logs"]["Row"];
export type VisitorSession = Database["public"]["Tables"]["visitor_sessions"]["Row"];
export type ExportLog = Database["public"]["Tables"]["export_logs"]["Row"];
export type MemberProfile = Database["public"]["Tables"]["member_profiles"]["Row"];
export type PromoCampaign = Database["public"]["Tables"]["promo_campaigns"]["Row"];
export type CommerceOffer = Database["public"]["Tables"]["commerce_offers"]["Row"];
export type Order = Database["public"]["Tables"]["orders"]["Row"];
export type OrderItem = Database["public"]["Tables"]["order_items"]["Row"];
export type AccessGrant = Database["public"]["Tables"]["access_grants"]["Row"];
export type DaypassCode = Database["public"]["Tables"]["daypass_codes"]["Row"];
export type PromoEntry = Database["public"]["Tables"]["promo_entries"]["Row"];
export type Listing = Database["public"]["Tables"]["listings"]["Row"];
export type DrawSnapshot = Database["public"]["Tables"]["draw_snapshots"]["Row"];
export type DrawResult = Database["public"]["Tables"]["draw_results"]["Row"];
export type OutboundEmail = Database["public"]["Tables"]["outbound_emails"]["Row"];
export type StripeWebhookEvent = Database["public"]["Tables"]["stripe_webhook_events"]["Row"];
export type PromoCampaignEntryCounter =
  Database["public"]["Tables"]["promo_campaign_entry_counters"]["Row"];
