export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admin_profiles: {
        Row: {
          id: string;
          email: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      landing_page_tests: {
        Row: {
          id: string;
          slug: string;
          status: string;
          internal_name: string;
          headline: string;
          subheadline: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string;
          price_display: string | null;
          category_focus: string | null;
          cta_primary: string | null;
          cta_secondary: string | null;
          modal_headline: string | null;
          modal_body: string | null;
          waitlist_cta: string | null;
          hero_image_url: string | null;
          config_json: Json;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          status?: string;
          internal_name: string;
          headline: string;
          subheadline?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          price_display?: string | null;
          category_focus?: string | null;
          cta_primary?: string | null;
          cta_secondary?: string | null;
          modal_headline?: string | null;
          modal_body?: string | null;
          waitlist_cta?: string | null;
          hero_image_url?: string | null;
          config_json?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          status?: string;
          internal_name?: string;
          headline?: string;
          subheadline?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          price_display?: string | null;
          category_focus?: string | null;
          cta_primary?: string | null;
          cta_secondary?: string | null;
          modal_headline?: string | null;
          modal_body?: string | null;
          waitlist_cta?: string | null;
          hero_image_url?: string | null;
          config_json?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      waitlist_leads: {
        Row: {
          id: string;
          email: string;
          email_normalized: string;
          first_name: string | null;
          source_landing_page_id: string | null;
          source_slug: string | null;
          anonymous_id: string | null;
          session_id: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          meta_campaign_id: string | null;
          meta_adset_id: string | null;
          meta_ad_id: string | null;
          offer_id: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string;
          fbclid: string | null;
          path: string | null;
          referrer: string | null;
          device_type: string | null;
          budget_range: string | null;
          buyer_seller_intent: string | null;
          likelihood_to_buy: string | null;
          consent_marketing: boolean;
          consent_marketing_at: string | null;
          privacy_version: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          email_normalized: string;
          first_name?: string | null;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          fbclid?: string | null;
          path?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          budget_range?: string | null;
          buyer_seller_intent?: string | null;
          likelihood_to_buy?: string | null;
          consent_marketing?: boolean;
          consent_marketing_at?: string | null;
          privacy_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          email_normalized?: string;
          first_name?: string | null;
          source_landing_page_id?: string | null;
          source_slug?: string | null;
          anonymous_id?: string | null;
          session_id?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string;
          fbclid?: string | null;
          path?: string | null;
          referrer?: string | null;
          device_type?: string | null;
          budget_range?: string | null;
          buyer_seller_intent?: string | null;
          likelihood_to_buy?: string | null;
          consent_marketing?: boolean;
          consent_marketing_at?: string | null;
          privacy_version?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_preferences: {
        Row: {
          id: string;
          lead_id: string | null;
          preference_type: string;
          preference_value: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id?: string | null;
          preference_type: string;
          preference_value: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string | null;
          preference_type?: string;
          preference_value?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      event_logs: {
        Row: {
          id: string;
          event_name: string;
          anonymous_id: string | null;
          session_id: string | null;
          lead_id: string | null;
          landing_page_id: string | null;
          landing_slug: string | null;
          offer_id: string | null;
          offer_type: string | null;
          price_cents: number | null;
          currency: string | null;
          path: string | null;
          url: string | null;
          referrer: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          fbclid: string | null;
          meta_campaign_id: string | null;
          meta_adset_id: string | null;
          meta_ad_id: string | null;
          device_type: string | null;
          properties: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_name: string;
          anonymous_id?: string | null;
          session_id?: string | null;
          lead_id?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string | null;
          path?: string | null;
          url?: string | null;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          device_type?: string | null;
          properties?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_name?: string;
          anonymous_id?: string | null;
          session_id?: string | null;
          lead_id?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          offer_id?: string | null;
          offer_type?: string | null;
          price_cents?: number | null;
          currency?: string | null;
          path?: string | null;
          url?: string | null;
          referrer?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          fbclid?: string | null;
          meta_campaign_id?: string | null;
          meta_adset_id?: string | null;
          meta_ad_id?: string | null;
          device_type?: string | null;
          properties?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      visitor_sessions: {
        Row: {
          id: string;
          session_id: string;
          anonymous_id: string;
          first_seen_at: string;
          last_seen_at: string;
          entry_path: string | null;
          landing_page_id: string | null;
          landing_slug: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_term: string | null;
          device_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          anonymous_id: string;
          first_seen_at?: string;
          last_seen_at?: string;
          entry_path?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          anonymous_id?: string;
          first_seen_at?: string;
          last_seen_at?: string;
          entry_path?: string | null;
          landing_page_id?: string | null;
          landing_slug?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_term?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      export_logs: {
        Row: {
          id: string;
          admin_user_id: string | null;
          export_type: string;
          filters_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_user_id?: string | null;
          export_type: string;
          filters_json?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          admin_user_id?: string | null;
          export_type?: string;
          filters_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type AdminProfile = Database["public"]["Tables"]["admin_profiles"]["Row"];
export type LandingPageTest = Database["public"]["Tables"]["landing_page_tests"]["Row"];
export type WaitlistLead = Database["public"]["Tables"]["waitlist_leads"]["Row"];
export type LeadPreference = Database["public"]["Tables"]["lead_preferences"]["Row"];
export type EventLog = Database["public"]["Tables"]["event_logs"]["Row"];
export type VisitorSession = Database["public"]["Tables"]["visitor_sessions"]["Row"];
export type ExportLog = Database["public"]["Tables"]["export_logs"]["Row"];
